# Generated by Django 5.0.7 on 2025-08-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LocationQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("query_text", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("display_name", models.TextField()),
            ],
        ),
    ]
